# Ensemble weights (3 signals)
LLM_WEIGHT = 0.50
STYLO_WEIGHT = 0.30
PHRASE_WEIGHT = 0.20

LABELS = {
    "likely_ai": (
        "AI-Generated — This piece shows strong signs of machine-generated writing. "
        "The phrasing, structure, and style closely match patterns typical of AI text. "
        "Creators can request a review if they believe this label is incorrect."
    ),
    "uncertain": (
        "Authorship Unclear — We couldn't confidently determine whether this was written "
        "by a person or generated by AI. The writing style falls in an ambiguous range. "
        "If you're the creator and this doesn't seem right, you can request a human review."
    ),
    "likely_human": (
        "Human-Written — This piece appears to be written by a person. The voice, rhythm, "
        "and word choices reflect natural human expression rather than machine-generated patterns."
    ),
}

CERTIFICATE_LABEL = (
    "[Verified Human Creator] — This creator completed a writing attestation and passed "
    "multi-signal review. This badge is separate from the standard transparency label above."
)

SIGNAL_DISAGREEMENT_THRESHOLD = 0.30
AI_LIKELIHOOD_AI_THRESHOLD = 0.75
AI_LIKELIHOOD_HUMAN_THRESHOLD = 0.39
DISAGREEMENT_HUMAN_OVERRIDE = 0.30


def combine_scores(
    llm_score: float,
    stylometric_score: float,
    phrase_score: float,
) -> float:
    """Weighted ensemble of three detection signals."""
    score = (
        (LLM_WEIGHT * llm_score)
        + (STYLO_WEIGHT * stylometric_score)
        + (PHRASE_WEIGHT * phrase_score)
    )
    return round(max(0.0, min(1.0, score)), 3)


def determine_attribution(
    ai_likelihood: float,
    llm_score: float,
    stylometric_score: float,
    phrase_score: float,
) -> str:
    """Map ensemble score and signal agreement to an attribution category."""
    scores = [llm_score, stylometric_score, phrase_score]
    signal_spread = max(scores) - min(scores)

    cross_signal_conflict = (
        (llm_score <= 0.35 and max(stylometric_score, phrase_score) >= 0.50)
        or (llm_score >= 0.70 and min(stylometric_score, phrase_score) <= 0.40)
    )

    if (
        signal_spread > SIGNAL_DISAGREEMENT_THRESHOLD or cross_signal_conflict
    ) and ai_likelihood > DISAGREEMENT_HUMAN_OVERRIDE:
        return "uncertain"

    if ai_likelihood <= AI_LIKELIHOOD_HUMAN_THRESHOLD:
        return "likely_human"

    if ai_likelihood >= AI_LIKELIHOOD_AI_THRESHOLD:
        return "likely_ai"

    return "uncertain"


def generate_label(attribution: str) -> str:
    """Map attribution category to transparency label text."""
    return LABELS.get(attribution, LABELS["uncertain"])


def generate_verified_label() -> str:
    """Return the provenance certificate badge text."""
    return CERTIFICATE_LABEL
