from signals.stylometrics import LLM_WEIGHT, STYLO_WEIGHT

LABELS = {
    "likely_ai": (
        "AI-Generated — This piece shows strong signs of machine-generated writing. "
        "The phrasing, structure, and style closely match patterns typical of AI text. "
        "Creators can request a review if they believe this label is incorrect."
    ),
    "uncertain": (
        "Authorship Unclear — We couldn't confidently determine whether this was written "
        "by a person or generated by AI. The writing style falls in an ambiguous range. "
        "If you're the creator and this doesn't seem right, you can request a human review."
    ),
    "likely_human": (
        "Human-Written — This piece appears to be written by a person. The voice, rhythm, "
        "and word choices reflect natural human expression rather than machine-generated patterns."
    ),
}

SIGNAL_DISAGREEMENT_THRESHOLD = 0.30
AI_LIKELIHOOD_AI_THRESHOLD = 0.75
AI_LIKELIHOOD_HUMAN_THRESHOLD = 0.39
DISAGREEMENT_HUMAN_OVERRIDE = 0.30


def combine_scores(llm_score: float, stylometric_score: float) -> float:
    """Combine both signals into a single ai_likelihood score."""
    score = (LLM_WEIGHT * llm_score) + (STYLO_WEIGHT * stylometric_score)
    return round(max(0.0, min(1.0, score)), 3)


def determine_attribution(
    ai_likelihood: float,
    llm_score: float,
    stylometric_score: float,
) -> str:
    """Map combined score and signal agreement to an attribution category."""
    signals_disagree = abs(llm_score - stylometric_score) > SIGNAL_DISAGREEMENT_THRESHOLD
    cross_signal_conflict = (
        llm_score <= 0.35 and stylometric_score >= 0.50
    ) or (
        llm_score >= 0.70 and stylometric_score <= 0.40
    )

    if (signals_disagree or cross_signal_conflict) and ai_likelihood > DISAGREEMENT_HUMAN_OVERRIDE:
        return "uncertain"

    if ai_likelihood <= AI_LIKELIHOOD_HUMAN_THRESHOLD:
        return "likely_human"

    if ai_likelihood >= AI_LIKELIHOOD_AI_THRESHOLD:
        return "likely_ai"

    return "uncertain"


def generate_label(attribution: str) -> str:
    """Map attribution category to transparency label text."""
    return LABELS.get(attribution, LABELS["uncertain"])
